
## Udemy Courses Analysis

#### Group Members
1. Paul Damocha
2. Jane Bahati
3. Audrey Kiage
4. Roy Njuguna


**Problem Statement:**

The objective of this analysis is to conduct a comprehensive evaluation of the course offerings on Udemy to gain insights into their subjects, pricing structures, and popularity. Specifically, we aim to:

1. Identify all the different subjects for which Udemy is offering courses.
2. Determine which subject has the maximum number of courses available.
3. Classify courses into two categories: free and paid.
4. Identify all paid courses and analyze their pricing.
5. Investigate sales data to identify the top-selling and least-selling courses.
6. Filter for graphic design courses priced below $100.
7. Compile a list of courses related to "Python."
8. Extract data on courses published in the year 2015.
9. Analyze the maximum number of subscribers for each level of the courses offered.

This analysis will provide a clearer understanding of the course landscape on Udemy, enabling better decision-making for potential learners and course developers.

In [26]:
# Importing necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [27]:
# Reading the dataset from a CSV file using pandas
data = pd.read_csv(r'udemy_courses_data.csv')

In [28]:
# Checking for duplicates
data.duplicated().sum()

6

In [29]:
# Dropping the duplicates
data.drop_duplicates(inplace=True)

In [30]:
# Confirming the duplicates are removed
data.duplicated().sum()

0

In [31]:
# Checking for null values
data.isna().sum()

course_id              0
course_title           0
is_paid                0
price                  0
num_subscribers        0
num_reviews            0
num_lectures           0
level                  0
content_duration       0
published_timestamp    0
subject                0
dtype: int64

In [32]:
# Checking the shape of the dataset
data.shape

(3676, 11)

## What are all the different subjects for which udemy is offering courses?

In [33]:
data.head()

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12T19:06:34Z,Musical Instruments
2,1193886,#12 Hand Coordination: Let your Hands dance wi...,True,75,482,1,47,Intermediate Level,1.5 hours,2017-04-26T18:34:57Z,Musical Instruments
3,1116700,#4 Piano Hand Coordination: Fun Piano Runs in ...,True,75,850,3,43,Intermediate Level,1 hour,2017-02-21T23:48:18Z,Musical Instruments
4,1120410,#5 Piano Hand Coordination: Piano Runs in 2 ...,True,75,940,3,32,Intermediate Level,37 mins,2017-02-21T23:44:49Z,Musical Instruments

In [34]:
# Getting information about our dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3676 entries, 0 to 3681
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   course_id            3676 non-null   int64
 1   course_title         3676 non-null   object
 2   is_paid              3676 non-null   bool
 3   price                3676 non-null   object
 4   num_subscribers      3676 non-null   int64
 5   num_reviews          3676 non-null   int64
 6   num_lectures         3676 non-null   int64
 7   level                3676 non-null   object
 8   content_duration     3676 non-null   object
 9   published_timestamp  3676 non-null   object
 10  subject              3676 non-null   object
dtypes: bool(1), int64(4), object(6)
memory usage: 448.5+ KB

In [35]:
# Retrieving the unique values from the 'subject' column of the DataFrame
data['subject'].unique()

array(['Musical Instruments', 'Business Finance', 'Graphic Design',
       'Web Development'], dtype=object)

## Which subject has the maximum number of courses?

In [36]:
# Finding the maximum value in the 'subject' column of the DataFrame
data['subject'].max()

'Web Development'

## Show all the courses which are free of cost

In [37]:
# Filtering the DataFrame to only include rows where the 'is_paid' column is False
data[data['is_paid'] == False]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
41,286070,5 lecciones que todo guitarrista debe tomar,False,Free,4452,263,14,Beginner Level,1 hour,2014-08-23T05:08:14Z,Musical Instruments
49,696630,"7 Ways A Beginner Guitarist Can Sound Better, ...",False,Free,4529,193,7,Beginner Level,36 mins,2015-12-21T18:50:50Z,Musical Instruments
57,955914,A beginner`s guide to fingerpicking and strumm...,False,Free,3481,29,20,Beginner Level,2 hours,2016-09-13T21:51:59Z,Musical Instruments
67,270976,A how to guide in HTML,False,Free,7318,205,8,Beginner Level,35 mins,2014-08-10T20:19:10Z,Web Development
74,1214144,¡Triunfar en La Bolsa de Valores No Requiere d...,False,Free,338,7,6,Beginner Level,1 hour,2017-05-30T14:30:12Z,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...
3620,552598,WordPress in under an hour - Create/manage you...,False,Free,6474,86,15,All Levels,1 hour,2015-07-15T00:21:56Z,Web Development
3638,1068590,Wordpress Website Mastery 2017,False,Free,5181,64,22,Beginner Level,2.5 hours,2017-01-18T17:01:40Z,Web Development
3652,752706,Write quicker HTML5 and CSS 3; productivity ha...,False,Free,13016,286,15,All Levels,1.5 hours,2016-03-03T17:45:31Z,Web Development
3674,1257976,Your First 10 Guitar Lessons - Learn how to pl...,False,Free,924,4,18,Beginner Level,1 hour,2017-06-29T00:29:36Z,Musical Instruments
3680,1225194,Zoho Books Gestion Financière d'Entreprise pas...,False,Free,229,0,33,All Levels,2 hours,2017-05-26T16:45:55Z,Business Finance

## Show all the courses which are paid

In [38]:
# Filtering the DataFrame to only include rows where the 'is_paid' column is True
data[data['is_paid'] == True]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12T19:06:34Z,Musical Instruments
2,1193886,#12 Hand Coordination: Let your Hands dance wi...,True,75,482,1,47,Intermediate Level,1.5 hours,2017-04-26T18:34:57Z,Musical Instruments
3,1116700,#4 Piano Hand Coordination: Fun Piano Runs in ...,True,75,850,3,43,Intermediate Level,1 hour,2017-02-21T23:48:18Z,Musical Instruments
4,1120410,#5 Piano Hand Coordination: Piano Runs in 2 ...,True,75,940,3,32,Intermediate Level,37 mins,2017-02-21T23:44:49Z,Musical Instruments
...,...,...,...,...,...,...,...,...,...,...,...
3676,498488,Your First Successful Forex Trades - With Case...,True,200,1079,34,16,All Levels,2.5 hours,2015-05-26T20:48:48Z,Business Finance
3677,328960,Your Own Site in 45 Min: The Complete Wordpres...,True,120,1566,29,36,All Levels,4 hours,2015-04-20T22:15:17Z,Web Development
3678,552700,Your Second Course on Piano: Two Handed Playing,True,70,1018,12,22,Beginner Level,5 hours,2015-10-26T20:04:21Z,Musical Instruments
3679,631754,Zend Framework 2: Learn the PHP framework ZF2 ...,True,40,723,130,37,All Levels,6.5 hours,2015-11-11T18:55:45Z,Web Development
3681,964478,Zombie Apocalypse Photoshop Actions,True,50,12,1,15,All Levels,1.5 hours,2016-09-26T22:19:48Z,Graphic Design

## Which are the top selling courses?

In [40]:
# Sorting the DataFrame by the 'num_subscribers' column in descending order
data.sort_values('num_subscribers', ascending=False)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
2230,41295,Learn HTML5 Programming From Scratch,False,Free,268923,8629,45,All Levels,10.5 hours,2013-02-14T07:03:41Z,Web Development
776,59014,Coding for Entrepreneurs Basic,False,Free,161029,279,27,Beginner Level,3.5 hours,2013-06-09T15:51:55Z,Web Development
3385,625204,The Web Developer Bootcamp,True,200,121584,27445,342,All Levels,43 hours,2015-11-02T21:13:27Z,Web Development
640,173548,Build Your First Website in 1 Week with HTML5 ...,False,Free,120291,5924,30,Beginner Level,3 hours,2014-04-08T16:21:30Z,Web Development
3316,764164,The Complete Web Developer Course 2.0,True,200,114512,22412,304,All Levels,30.5 hours,2016-03-08T22:28:36Z,Web Development
...,...,...,...,...,...,...,...,...,...,...,...
403,1221942,Basic Bookkeeping,True,35,0,0,12,Beginner Level,44 mins,2017-05-23T16:20:18Z,Business Finance
2596,185526,MicroStation - Células,True,20,0,0,9,Beginner Level,37 mins,2014-04-15T21:48:55Z,Graphic Design
994,603902,Curso de Didgeridoo nivel principiante,True,50,0,0,31,Beginner Level,1 hour,2016-04-11T04:14:05Z,Musical Instruments
476,1252410,Beginners Guide to Kindle Ebook Covers Design ...,True,20,0,0,16,All Levels,1.5 hours,2017-06-19T19:26:46Z,Graphic Design
2418,1058852,Learn to trade using technical analysis,True,50,0,0,6,Intermediate Level,32 mins,2017-05-02T13:15:53Z,Business Finance

## Which are the least selling courses?

In [41]:
# Sorting the DataFrame by the 'num_subscribers' column in ascending order
data.sort_values('num_subscribers', ascending=True)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
2290,1223240,Learn Pirates of the Caribbean by Ear on the P...,True,20,0,0,6,All Levels,32 mins,2017-05-22T17:14:43Z,Musical Instruments
3261,1275872,The Complete Adobe Spark Course,True,150,0,0,29,All Levels,2 hours,2017-07-03T17:39:57Z,Graphic Design
491,1251582,Best Practices in Corporate Budgeting,True,50,0,0,9,Intermediate Level,2 hours,2017-06-29T22:01:56Z,Business Finance
484,1032648,beginning accounting,True,20,0,0,12,Intermediate Level,38 mins,2016-12-26T16:52:47Z,Business Finance
91,1265814,ABRSM Grade III Piano Class - Handel Sonatina ...,True,20,0,0,5,Beginner Level,31 mins,2017-07-06T16:12:34Z,Musical Instruments
...,...,...,...,...,...,...,...,...,...,...,...
3316,764164,The Complete Web Developer Course 2.0,True,200,114512,22412,304,All Levels,30.5 hours,2016-03-08T22:28:36Z,Web Development
640,173548,Build Your First Website in 1 Week with HTML5 ...,False,Free,120291,5924,30,Beginner Level,3 hours,2014-04-08T16:21:30Z,Web Development
3385,625204,The Web Developer Bootcamp,True,200,121584,27445,342,All Levels,43 hours,2015-11-02T21:13:27Z,Web Development
776,59014,Coding for Entrepreneurs Basic,False,Free,161029,279,27,Beginner Level,3.5 hours,2013-06-09T15:51:55Z,Web Development
2230,41295,Learn HTML5 Programming From Scratch,False,Free,268923,8629,45,All Levels,10.5 hours,2013-02-14T07:03:41Z,Web Development

## Show all the courses of graphic design where the price is below 100

In [44]:
# Filtering the DataFrame to include only courses in the 'Graphic Design' subject with a price less than 100
data[(data['subject'] == 'Graphic Design') & (data['price'] < '100')]

Empty DataFrame
Columns: [course_id, course_title, is_paid, price, num_subscribers, num_reviews, num_lectures, level, content_duration, published_timestamp, subject]
Index: []

## List all the courses that are related with "Python".

In [67]:
# Filtering the DataFrame to include only courses whose titles contain the word 'Python'
python_courses = data[data['course_title'].str.contains('Python' or 'python')]
python_courses.shape

(29, 12)

## What are the courses published in the year 2015?

In [19]:
# Displaying the data types of each column in the DataFrame
data.dtypes

course_id               int64
course_title           object
is_paid                  bool
price                  object
num_subscribers         int64
num_reviews             int64
num_lectures            int64
level                  object
content_duration       object
published_timestamp    object
subject                object
dtype: object

In [56]:
# Converting the 'published_timestamp' column to datetime format
data['published_timestamp'] = pd.to_datetime(data['published_timestamp'])

In [57]:
# Extracting the year from the 'published_timestamp' column and creating a new column 'Year'
data['Year'] = data['published_timestamp'].dt.year

In [22]:
# Filtering the DataFrame to include only rows where the 'Year' column is 2015
data[data['Year'] == 2015]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,Year
10,591880,1 - Concepts of Statistics For Beginners Step ...,True,200,273,4,15,Beginner Level,31 mins,2015-08-30 22:48:34+00:00,Business Finance,2015
16,302450,10 Numbers Every Business Owner Should Know,True,20,13,1,9,All Levels,1 hour,2015-03-08 19:11:24+00:00,Business Finance,2015
19,384928,101 Blues riffs - learn how the harmonica supe...,True,200,1350,65,55,Intermediate Level,6.5 hours,2015-01-04 21:14:31+00:00,Musical Instruments,2015
23,550842,16 Guitar Chords to Jam With - (Beginner - Int...,True,20,1224,19,20,Beginner Level,1 hour,2015-07-10 19:53:56+00:00,Musical Instruments,2015
26,486240,2 Easy Steps To Investment And Avoiding Traps,True,20,828,1,20,All Levels,1 hour,2015-04-27 23:18:59+00:00,Business Finance,2015
...,...,...,...,...,...,...,...,...,...,...,...,...
3675,551170,Your First Course on Piano,True,70,2002,34,33,Beginner Level,4 hours,2015-07-16 17:07:49+00:00,Musical Instruments,2015
3676,498488,Your First Successful Forex Trades - With Case...,True,200,1079,34,16,All Levels,2.5 hours,2015-05-26 20:48:48+00:00,Business Finance,2015
3677,328960,Your Own Site in 45 Min: The Complete Wordpres...,True,120,1566,29,36,All Levels,4 hours,2015-04-20 22:15:17+00:00,Web Development,2015
3678,552700,Your Second Course on Piano: Two Handed Playing,True,70,1018,12,22,Beginner Level,5 hours,2015-10-26 20:04:21+00:00,Musical Instruments,2015
3679,631754,Zend Framework 2: Learn the PHP framework ZF2 ...,True,40,723,130,37,All Levels,6.5 hours,2015-11-11 18:55:45+00:00,Web Development,2015

## What are the maximum number of subscribers for each level of the courses?

In [63]:
# Retrieving the unique values from the 'level' column of the DataFrame
data['level'].unique()

array(['All Levels', 'Intermediate Level', 'Beginner Level',
       'Expert Level'], dtype=object)

In [64]:
# Grouping the DataFrame by the 'level' column and calculating the maximum number of subscribers for each level
data.groupby('level')['num_subscribers'].max()

level
All Levels            268923
Beginner Level        161029
Expert Level            5172
Intermediate Level     29167
Name: num_subscribers, dtype: int64

## Conclusion
- The top selling courses are web development courses
- The least selling courses are Musical instruments, Business finance and graphic design
- The different subjects offered are Musical Instruments', 'Business Finance', 'Graphic Design', 'Web Development'
- 310 courses are free of charge and 3366 courses are paid
- There are no graphic design courses where the price is below 100
- 29 courses have the keyword 'Python'
- 1014 courses were published in 2015

## Recommendations

Based on the provided conclusions, here are some formulated recommendations:

1. **Expand Web Development Offerings**: Since web development courses are the top sellers, consider increasing the variety and depth of these courses. This could include advanced topics, specialized frameworks, or niche areas within web development to cater to diverse learner interests.

2. **Revamp Underperforming Courses**: For the least selling courses (Musical Instruments, Business Finance, and Graphic Design), analyze their content and market demand. Consider redesigning these courses to make them more appealing, such as incorporating practical projects, industry insights, or collaboration with professionals in those fields.

3. **Bundle Free Courses**: With 310 free courses available, consider creating bundled offerings that include popular free courses alongside introductory paid courses. This could attract new users who are hesitant to pay and could lead to upselling opportunities.

4. **Price Adjustments for Graphic Design**: Given that there are no graphic design courses priced below $100, consider introducing lower-priced options or entry-level courses to attract more learners. This could help capture a broader audience interested in graphic design.

5. **Promote Python Courses**: With 29 courses containing the keyword "Python," leverage the popularity of Python by enhancing marketing efforts. Highlight these courses in promotions, especially given Python's relevance in data science and web development.

6. **Update Course Content from 2015**: With 1,014 courses published in 2015, review and update these courses to ensure that the content reflects current trends, tools, and technologies. Regularly updating course content can enhance engagement and improve sales.

7. **Conduct Market Research**: Perform a market analysis to understand why certain subjects are underperforming. Gathering feedback from learners can provide insights into potential improvements and new course ideas that align with current industry demands.

8. **Leverage Successful Subjects**: Use the success of web development courses to cross-promote related subjects, such as full-stack development or mobile app development, to capitalize on the interest in web technologies.

Implementing these recommendations can help improve overall course performance, attract more learners, and increase revenue.